
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'Pkg.add("Documenter"); ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("OpenDSSDirect")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("OpenDSSDirect")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("OpenDSSDirect")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'